/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Gigara Hettige
 */

// Generated by scripts/generate-vscode-css-vars.mjs
// Sources:
// - https://raw.githubusercontent.com/microsoft/vscode/main/extensions/theme-defaults/themes/dark_vs.json
// - https://raw.githubusercontent.com/microsoft/vscode/main/extensions/theme-defaults/themes/dark_plus.json
// - https://raw.githubusercontent.com/microsoft/vscode/main/extensions/theme-defaults/themes/light_vs.json
// - https://raw.githubusercontent.com/microsoft/vscode/main/extensions/theme-defaults/themes/light_plus.json

export type VSCodeCssVariableName = `--vscode-${string}`;

export type VSCodeCssVariables = Partial<Record<VSCodeCssVariableName, string>>;

export const VSCODE_DARK_PLUS_CSS_VARIABLES: VSCodeCssVariables = {
  "--vscode-actionBar-toggledBackground": "#383a49",
  "--vscode-activityBarBadge-background": "#007ACC",
  "--vscode-checkbox-border": "#6B6B6B",
  "--vscode-editor-background": "#1E1E1E",
  "--vscode-editor-font-family": "-apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', sans-serif",
  "--vscode-editor-font-feature-settings": "normal",
  "--vscode-editor-font-size": "13px",
  "--vscode-editor-font-weight": "normal",
  "--vscode-editor-foreground": "#D4D4D4",
  "--vscode-editor-inactiveSelectionBackground": "#3A3D41",
  "--vscode-editor-selectionHighlightBackground": "#ADD6FF26",
  "--vscode-editorIndentGuide-activeBackground1": "#707070",
  "--vscode-editorIndentGuide-background1": "#404040",
  "--vscode-font-family": "-apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', sans-serif",
  "--vscode-font-size": "13px",
  "--vscode-font-weight": "normal",
  "--vscode-input-placeholderForeground": "#A6A6A6",
  "--vscode-list-activeSelectionIconForeground": "#FFF",
  "--vscode-list-dropBackground": "#383B3D",
  "--vscode-menu-background": "#252526",
  "--vscode-menu-border": "#454545",
  "--vscode-menu-foreground": "#CCCCCC",
  "--vscode-menu-selectionBackground": "#0078d4",
  "--vscode-menu-separatorBackground": "#454545",
  "--vscode-ports-iconRunningProcessForeground": "#369432",
  "--vscode-sideBarSectionHeader-background": "#0000",
  "--vscode-sideBarSectionHeader-border": "#ccc3",
  "--vscode-sideBarTitle-foreground": "#BBBBBB",
  "--vscode-statusBarItem-remoteBackground": "#16825D",
  "--vscode-statusBarItem-remoteForeground": "#FFF",
  "--vscode-tab-lastPinnedBorder": "#ccc3",
  "--vscode-tab-selectedBackground": "#222222",
  "--vscode-tab-selectedForeground": "#ffffffa0",
  "--vscode-terminal-inactiveSelectionBackground": "#3A3D41",
  "--vscode-widget-border": "#303031"
};

export const VSCODE_LIGHT_PLUS_CSS_VARIABLES: VSCodeCssVariables = {
  "--vscode-actionBar-toggledBackground": "#dddddd",
  "--vscode-activityBarBadge-background": "#007ACC",
  "--vscode-checkbox-border": "#919191",
  "--vscode-diffEditor-unchangedRegionBackground": "#f8f8f8",
  "--vscode-editor-background": "#FFFFFF",
  "--vscode-editor-font-family": "-apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', sans-serif",
  "--vscode-editor-font-feature-settings": "normal",
  "--vscode-editor-font-size": "13px",
  "--vscode-editor-font-weight": "normal",
  "--vscode-editor-foreground": "#000000",
  "--vscode-editor-inactiveSelectionBackground": "#E5EBF1",
  "--vscode-editor-selectionHighlightBackground": "#ADD6FF80",
  "--vscode-editorIndentGuide-activeBackground1": "#939393",
  "--vscode-editorIndentGuide-background1": "#D3D3D3",
  "--vscode-editorSuggestWidget-background": "#F3F3F3",
  "--vscode-font-family": "-apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', sans-serif",
  "--vscode-font-size": "13px",
  "--vscode-font-weight": "normal",
  "--vscode-input-placeholderForeground": "#767676",
  "--vscode-list-activeSelectionIconForeground": "#FFF",
  "--vscode-list-focusAndSelectionOutline": "#90C2F9",
  "--vscode-list-hoverBackground": "#E8E8E8",
  "--vscode-menu-border": "#D4D4D4",
  "--vscode-notebook-cellBorderColor": "#E8E8E8",
  "--vscode-notebook-selectedCellBackground": "#c8ddf150",
  "--vscode-ports-iconRunningProcessForeground": "#369432",
  "--vscode-searchEditor-textInputBorder": "#CECECE",
  "--vscode-settings-numberInputBorder": "#CECECE",
  "--vscode-settings-textInputBorder": "#CECECE",
  "--vscode-sideBarSectionHeader-background": "#0000",
  "--vscode-sideBarSectionHeader-border": "#61616130",
  "--vscode-sideBarTitle-foreground": "#6F6F6F",
  "--vscode-statusBarItem-errorBackground": "#c72e0f",
  "--vscode-statusBarItem-remoteBackground": "#16825D",
  "--vscode-statusBarItem-remoteForeground": "#FFF",
  "--vscode-tab-lastPinnedBorder": "#61616130",
  "--vscode-tab-selectedBackground": "#ffffffa5",
  "--vscode-tab-selectedForeground": "#333333b3",
  "--vscode-terminal-inactiveSelectionBackground": "#E5EBF1",
  "--vscode-widget-border": "#d4d4d4"
};
